# User
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR=yellow

# Dir
SPACESHIP_DIR_COLOR=209

# Async
SPACESHIP_ASYNC_SYMBOL=''

# Char
SPACESHIP_CHAR_SYMBOL_FAILURE=' '
SPACESHIP_CHAR_COLOR_SUCCESS=184
