# User
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR=yellow

# Dir
SPACESHIP_DIR_COLOR=209

# Async
SPACESHIP_PROMPT_ASYNC=FALSE
SPACESHIP_ASYNC_SYMBOL=''

# Char
SPACESHIP_CHAR_SYMBOL=''
SPACESHIP_CHAR_SYMBOL_FAILURE=''
